### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by henuliulei** [var-rain/MatchTemplate#1]
大佬，运行你的程序报了个无法加载 DLL“MatchNative.dll”: 找不到指定的模块。请问大佬MatchNative.dll是啥，系统好像没有这个dll文件吧。

**Comment by var-rain** [comment]
> 大佬，运行你的程序报了个无法加载 DLL“MatchNative.dll”: 找不到指定的模块。请问大佬MatchNative.dll是啥，系统好像没有这个dll文件吧。

这本来就是一个不能运行的程序,只是我临时起意建立的一个项目而已,本来想慢慢的完善,但是后来忙,没时间,结果就逐渐被遗忘了
